# -*- coding: utf-8 -*-
"""BERT_KeyTopics_NLP_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/194IhIhWkHILb157h490KrXL7_qhtkEbM

### Script 2.5, A Nambiar
### Topic Detection: BERT
"""

#pip install bertopic

import pandas as pd
import pyarrow
import re

from bertopic import BERTopic
from joblib import Parallel, delayed
from sklearn.feature_extraction.text import CountVectorizer

import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_parquet('/content/drive/MyDrive/sample_preprocessed_news_final_1.parquet')
df.head()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# df['important_words'] = df['important_words'].str.lower()
# word_list = df['important_words'].tolist()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# #min_topic_size=30
# 
# modelBert = BERTopic(calculate_probabilities=True, verbose=True, nr_topics=None, top_n_words= 15)
# topics, probs = modelBert.fit_transform(word_list)

topic_freq = modelBert.get_topic_freq()
num_topics = len(topic_freq)
print("Number of Topics:", num_topics)

freq = modelBert.get_topic_info()

print(f"Topics: {freq.shape[0]}")
freq.head(17)

for topic_id in range(num_topics):
    topic_words = modelBert.get_topic(topic_id)
    print(f"Topic {topic_id}: {topic_words}")

modelBert.visualize_topics()

modelBert.get_topic_freq()

modelBert.visualize_barchart(top_n_topics=17)

df.shape

df['bert_topic'] = topics
df.shape

"""Topic 0: Market Analysis and Research: This topic is focused on market analysis and research, including reports, global trends, growth, intelligence, and key players in various industries.

Topic 1: Healthcare and Medical AI: This topic revolves around healthcare and medical applications of AI, including topics such as patient care, clinical research, imaging, and drug development.

Topic 2: Chatbots and AI in Technology: This topic explores the use of AI in technology, particularly in the context of chatbots, search engines, and the influence of companies like Microsoft, Google, and OpenAI.

Topic 3: Ethical Considerations of AI: This topic delves into the ethical implications of AI, discussing topics such as advice, human rights, the potential for unethical use of AI systems, cybersecurity, and military applications.

Topic 4: AI and Cloud Computing: This topic focuses on the intersection of AI and cloud computing, including discussions on data processing, machine learning, real-time processing, and the role of companies like Qualcomm and Realme.

Topic 5: AI in Digital Transformation: This topic centers around the impact of AI on digital transformation, customer experiences, data-driven platforms, and the potential for automation and innovation in various industries.

Topic 6: AI in Climate and Environmental Sciences: This topic explores the role of AI in climate and environmental sciences, discussing flood monitoring, climate change, data analysis, and the use of AI for better understanding and decision-making.

Topic 7: Stock Market and Investments: This topic focuses on the stock market, investments, and financial trends, discussing shares, funds, soundhound, institutional investors, and average quarterly performance.

Topic 8: AI in Art and Creativity: This topic revolves around the intersection of AI and art, discussing creative applications, style generation, streetwear, design, and the impact of AI on artistic work and creativity.

Topic 9: AI and Search Engines: This topic explores the use of AI in search engines, discussing companies like Google, Baidu, Bing, and the role of AI in improving search results, language processing, and user experience.

Topic 10: Elon Musk, Tesla, and AI: This topic centers around Elon Musk, Tesla, and their involvement in AI advancements, autonomous driving, and the impact of AI technologies on the automotive industry.

Topic 11: AI in Education and Academic Writing: This topic focuses on the use of AI in education, discussing applications such as generative models, essay writing, plagiarism detection, and the potential impact of AI on student learning and academic integrity.

Topic 12: NVIDIA, GPUs, and AI Computing: This topic explores the role of NVIDIA, GPUs, and AI computing, discussing stock performance, cloud computing, data processing, and the impact of NVIDIA's technology on the AI landscape.

Topic 13: AI in Music and Audio: This topic revolves around the intersection of AI and the music industry, discussing platforms like Spotify, AI-generated music, voice assistants, and the impact of AI on the creation and consumption of music.

Topic 14: AI Policy and International Implications: This topic explores AI policy and its international implications, discussing topics such as AI adoption in India, OECDAI initiatives, national policies, and the impact of AI on different countries.

Topic 15: AI in Education and Skill Development: This topic focuses on AI in education and skill development, discussing programs, university research, data science skills, and the role of AI in shaping the future of education.
"""

import matplotlib.pyplot as plt

df.head()

df[df['bert_topic'] == 2]

modelBert.get_topic_info()

#df[df['bert_topic'] == 2]

topic_2_df = df[df['bert_topic'] == 2]
topic_2_freq = topic_2_df['date'].value_counts().sort_index()
#topic_2_freq

# topic_2_df = df[df['bert_topic'] == 2]
# topic_2_freq = topic_2_df['date'].value_counts().sort_index()

# plt.figure(figsize=(10, 6))
# topic_2_freq.plot(kind='line')
# plt.xlabel('Publication Date')
# plt.ylabel('Frequency')
# plt.title('Publication Frequency of AI Chatbots Over Time')
# plt.xlim(['2023-01-01', '2023-04-30']) 
# plt.grid(True)
# plt.show()

# topic_9_df = df[df['bert_topic'] == 9]
# topic_9_freq = topic_9_df['date'].value_counts().sort_index()

# plt.figure(figsize=(10, 6))
# topic_9_freq.plot(kind='line')
# plt.xlabel('Publication Date')
# plt.ylabel('Frequency')
# plt.title('Publication Frequency of AI in Search Engines Over Time')
# plt.xlim(['2023-01-01', '2023-04-30']) 
# plt.grid(True)
# plt.show()

# topic_15_df = df[df['bert_topic'] == 15]
# topic_15_freq = topic_15_df['date'].value_counts().sort_index()

# plt.figure(figsize=(10, 6))
# topic_15_freq.plot(kind='line')
# plt.xlabel('Publication Date')
# plt.ylabel('Frequency')
# plt.title('Publication Frequency of AI in Education Over Time')
# plt.xlim(['2021-01-01', '2023-04-30']) 
# plt.grid(True)
# plt.show()

# topic_df = df[df['bert_topic'] == 3]
# topic_freq = topic_df['date'].value_counts().sort_index()

# plt.figure(figsize=(10, 6))
# topic_freq.plot(kind='line')
# plt.xlabel('Publication Date')
# plt.ylabel('Frequency')
# plt.title('Publication Frequency of AI for Human Rights Over Time')
# plt.xlim(['2023-01-01', '2023-04-30']) 
# plt.grid(True)
# plt.show()

# topic_df = df[df['bert_topic'] == 1]
# topic_freq = topic_df['date'].value_counts().sort_index()

# plt.figure(figsize=(10, 6))
# topic_freq.plot(kind='line')
# plt.xlabel('Publication Date')
# plt.ylabel('Frequency')
# plt.title('Publication Frequency of AI in Healthcare Over Time')
# plt.xlim(['2023-01-01', '2023-04-30']) 
# plt.grid(True)
# plt.show()

# topic_df = df[df['bert_topic'] == 8]
# topic_freq = topic_df['date'].value_counts().sort_index()

# plt.figure(figsize=(10, 6))
# topic_freq.plot(kind='line')
# plt.xlabel('Publication Date')
# plt.ylabel('Frequency')
# plt.title('Publication Frequency of AI in Art Over Time')
# plt.xlim(['2023-01-01', '2023-04-30']) 
# plt.grid(True)
# plt.show()

# import pyarrow as pa
# import pyarrow.parquet as pq

# df.head()

# table = pa.Table.from_pandas(df)

# local_path = '/content/drive/MyDrive/BERT_topic_df.parquet'
# pq.write_table(table, local_path)

import os

os.environ['LC_ALL'] = 'en_US.UTF-8'

# !jupyter nbconvert --to html /content/BERT_KeyTopics_NLP_Final.ipynb